### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by jrcollin** [mauriciotogneri/dapackages#4]
Is there a timeline to add null safety support? The current plug-in has issues when Dart is set to >=2.12

**Comment by mauriciotogneri** [comment]
Hi @jrcollin 
I have published a new version that supports null safety:
https://pub.dev/packages/dapackages/versions/1.5.0-nullsafety.0
Let me know if you encounter any issue.

**Comment by jrcollin** [comment]
Hi Mauricio,
Thank's a lot for your fast response.

**Comment by mauriciotogneri** [comment]
@jrcollin 
Can we close this issue?

**Comment by jrcollin** [comment]
Yes every everything works fine on Mac and Windows.
Thanks again
